export const browserCoreExamples = [
  "verso browser status",
  "verso browser start",
  "verso browser stop",
  "verso browser tabs",
  "verso browser open https://example.com",
  "verso browser focus abcd1234",
  "verso browser close abcd1234",
  "verso browser screenshot",
  "verso browser screenshot --full-page",
  "verso browser screenshot --ref 12",
  "verso browser snapshot",
  "verso browser snapshot --format aria --limit 200",
  "verso browser snapshot --efficient",
  "verso browser snapshot --labels",
];

export const browserActionExamples = [
  "verso browser navigate https://example.com",
  "verso browser resize 1280 720",
  "verso browser click 12 --double",
  'verso browser type 23 "hello" --submit',
  "verso browser press Enter",
  "verso browser hover 44",
  "verso browser drag 10 11",
  "verso browser select 9 OptionA OptionB",
  "verso browser upload /tmp/file.pdf",
  'verso browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "verso browser dialog --accept",
  'verso browser wait --text "Done"',
  "verso browser evaluate --fn '(el) => el.textContent' --ref 7",
  "verso browser console --level error",
  "verso browser pdf",
];
