import type { EventCategory, ThreatLevel } from "./types.js";

export const THREAT_PRIORITY: Record<ThreatLevel, number> = {
  critical: 5,
  high: 4,
  medium: 3,
  low: 2,
  info: 1,
};

type KeywordMap = Record<string, EventCategory>;

export const CRITICAL_KEYWORDS: KeywordMap = {
  "nuclear strike": "military",
  "nuclear attack": "military",
  "nuclear war": "military",
  invasion: "conflict",
  "declaration of war": "conflict",
  "martial law": "military",
  coup: "military",
  "coup attempt": "military",
  genocide: "conflict",
  "ethnic cleansing": "conflict",
  "chemical attack": "terrorism",
  "biological attack": "terrorism",
  "dirty bomb": "terrorism",
  "mass casualty": "conflict",
  "pandemic declared": "health",
  "health emergency": "health",
  "nato article 5": "military",
  "evacuation order": "disaster",
  meltdown: "disaster",
  "nuclear meltdown": "disaster",
};

export const HIGH_KEYWORDS: KeywordMap = {
  war: "conflict",
  "armed conflict": "conflict",
  airstrike: "conflict",
  "air strike": "conflict",
  "drone strike": "conflict",
  missile: "military",
  "missile launch": "military",
  "troops deployed": "military",
  "military escalation": "military",
  bombing: "conflict",
  casualties: "conflict",
  hostage: "terrorism",
  terrorist: "terrorism",
  "terror attack": "terrorism",
  assassination: "crime",
  "cyber attack": "cyber",
  ransomware: "cyber",
  "data breach": "cyber",
  sanctions: "economic",
  embargo: "economic",
  earthquake: "disaster",
  tsunami: "disaster",
  hurricane: "disaster",
  typhoon: "disaster",
};

export const MEDIUM_KEYWORDS: KeywordMap = {
  protest: "protest",
  protests: "protest",
  riot: "protest",
  riots: "protest",
  unrest: "protest",
  demonstration: "protest",
  "strike action": "protest",
  "military exercise": "military",
  "naval exercise": "military",
  "arms deal": "military",
  "weapons sale": "military",
  "diplomatic crisis": "diplomatic",
  "ambassador recalled": "diplomatic",
  "expel diplomats": "diplomatic",
  "trade war": "economic",
  tariff: "economic",
  recession: "economic",
  inflation: "economic",
  "market crash": "economic",
  flood: "disaster",
  flooding: "disaster",
  wildfire: "disaster",
  volcano: "disaster",
  eruption: "disaster",
  outbreak: "health",
  epidemic: "health",
  "infection spread": "health",
  "oil spill": "environmental",
  "pipeline explosion": "infrastructure",
  blackout: "infrastructure",
  "power outage": "infrastructure",
  "internet outage": "infrastructure",
  derailment: "infrastructure",
};

export const LOW_KEYWORDS: KeywordMap = {
  election: "diplomatic",
  vote: "diplomatic",
  referendum: "diplomatic",
  summit: "diplomatic",
  treaty: "diplomatic",
  agreement: "diplomatic",
  negotiation: "diplomatic",
  talks: "diplomatic",
  peacekeeping: "diplomatic",
  "humanitarian aid": "diplomatic",
  ceasefire: "diplomatic",
  "peace treaty": "diplomatic",
  "climate change": "environmental",
  emissions: "environmental",
  pollution: "environmental",
  deforestation: "environmental",
  drought: "environmental",
  vaccine: "health",
  vaccination: "health",
  disease: "health",
  virus: "health",
  "public health": "health",
  covid: "health",
  "interest rate": "economic",
  gdp: "economic",
  unemployment: "economic",
  regulation: "economic",
};

export const TECH_HIGH_KEYWORDS: KeywordMap = {
  "major outage": "infrastructure",
  "service down": "infrastructure",
  "global outage": "infrastructure",
  "zero-day": "cyber",
  "critical vulnerability": "cyber",
  "supply chain attack": "cyber",
  "mass layoff": "economic",
};

export const TECH_MEDIUM_KEYWORDS: KeywordMap = {
  outage: "infrastructure",
  breach: "cyber",
  hack: "cyber",
  vulnerability: "cyber",
  layoff: "economic",
  layoffs: "economic",
  antitrust: "economic",
  monopoly: "economic",
  ban: "economic",
  shutdown: "infrastructure",
};

export const TECH_LOW_KEYWORDS: KeywordMap = {
  ipo: "economic",
  funding: "economic",
  acquisition: "economic",
  merger: "economic",
  launch: "tech",
  release: "tech",
  update: "tech",
  partnership: "economic",
  startup: "tech",
  "ai model": "tech",
  "open source": "tech",
};

export const EXCLUSIONS = [
  "protein",
  "couples",
  "relationship",
  "dating",
  "diet",
  "fitness",
  "recipe",
  "cooking",
  "shopping",
  "fashion",
  "celebrity",
  "movie",
  "tv show",
  "sports",
  "game",
  "concert",
  "festival",
  "wedding",
  "vacation",
  "travel tips",
  "life hack",
  "self-care",
  "wellness",
];

export const SHORT_KEYWORDS = new Set([
  "war",
  "coup",
  "ban",
  "vote",
  "riot",
  "riots",
  "hack",
  "talks",
  "ipo",
  "gdp",
  "virus",
  "disease",
  "flood",
]);
